name: Continuous Integration
on: push

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js 16.x
        uses: actions/setup-node@v1.3.0
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Testing
        run: npm test
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js 16.x
        uses: actions/setup-node@v1.3.0
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
