name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      env:
        type: string
        default: dev
        required: true
        description: 実行環境

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: print-env
        run: echo "${{ inputs.env }}"
