name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      env:
        type: string
        default: dev
        required: true
        description: 実行環境

jobs:
  print-env:
    name: print env
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.env }}"
